name = "follow-email-worker"
compatibility_date = "2025-07-16"

[env.prod.vars]
API_URL = "https://api.folo.is"
INBOXES_AUTH_TOKEN = ""
INBOXES_EMAIL = "@follow.re"
SUCCESS_FORWARD_TO = "followadmin+success@rss3.io"
FAILURE_FORWARD_TO = "followadmin+failure@rss3.io"

[env.dev.vars]
API_URL = "https://api.dev.follow.is"
INBOXES_AUTH_TOKEN = ""
INBOXES_EMAIL = "__devdev@follow.re"
SUCCESS_FORWARD_TO = "followadmin+success@rss3.io"
FAILURE_FORWARD_TO = "followadmin+failure@rss3.io"

[observability.logs]
enabled = true